"""
ltl_to_constraints.py — Convert non-temporal LTL to evaluable Python violation expressions.

Overview
--------
This module handles one specific class of LTL formulas: those wrapped in the
temporal operators "always" (□) and "never" (¬◇ / □¬). These are the
*time-invariant* properties — predicates that must hold (or must not hold)
at every individual timestep, independently of execution history.

Why only non-temporal?
----------------------
The full LTL specification extracted from a SysML v2 model contains both
time-invariant and genuinely temporal properties:

    Time-invariant (handled here):
        □(pump_on → valve_open)           "always: pump implies valve"
        □(|roll| ≤ 30°)                   "always: bounded attitude"

    Temporal (NOT handled here):
        ◇(|transferred - target| ≤ 2L)   "eventually reach goal"
        φ U ψ                              "φ until ψ"

The temporal properties require reasoning over execution traces, which cannot
be reduced to a per-step boolean check. Those are verified downstream by
nuXmv, which model-checks the full LTL specification over a finite transition
system abstraction of the trained controller.

The non-temporal properties serve a dual role in the pipeline:

    1. RL REWARD SIGNAL (this module)
       During training, each time-invariant property becomes a per-step
       violation check. If the agent's action causes any invariant to break,
       the episode receives a -1 reward and terminates. This is the sparse
       reward formulation described in the paper — no shaping, no intermediate
       signals, just -1 / 0 / +1.

    2. TRANSITION CONSTRAINTS FOR VERIFICATION (downstream, nuXmv)
       After training, the same non-temporal properties constrain the finite
       transition system that nuXmv searches. Each state transition in the
       abstraction is only valid if it satisfies all verified time-invariant
       properties. This is what makes the two-phase verification tractable:
       β-CROWN verifies each non-temporal property holds for every valid
       input on a single forward pass, then nuXmv only needs to explore
       transitions that respect those verified bounds. The non-temporal
       properties prune the transition space so that temporal model checking
       remains feasible for networks with hundreds of neurons.

       Without this pruning, nuXmv would face an intractably large state
       space. The non-temporal properties act as a contract: "these
       conditions are guaranteed per-step, so only check temporal sequences
       within that envelope."

Why violation expressions (True = bad)?
---------------------------------------
We chose to output expressions where eval() == True means a constraint is
VIOLATED, rather than expressions where False means violated. Two reasons:

    1. Direct reward mapping. The RL check becomes:
           if eval(expr, ns): return -1.0
       No negation to think about, no off-by-one in the logic.

    2. Natural readability. The violation of "pump on implies valve open"
       is "pump on AND valve closed" — the thing that went wrong. This reads
       more naturally when debugging failed episodes than "not (not pump_on
       or valve_open)".

The negation of common LTL patterns:

    always(A implies B)  →  violation:  A and not B
    always(A iff B)      →  violation:  A != B
    always(φ)            →  violation:  not (φ)
    never(φ)             →  violation:  φ          (already the bad thing)

Why eval() and not compiled lambdas?
------------------------------------
eval() with string expressions was chosen over pre-compiled functions for:

    - Inspectability. The violation list is human-readable. During debugging
      or logging you can print the exact expression that fired. A lambda
      is opaque.
    - Serialization. Strings round-trip through JSON, config files, and logs.
      Lambdas do not.
    - Simplicity. The SysML extractor produces structured text. Converting
      to a Python string is one step. Converting to an AST or lambda adds
      machinery with no benefit at our scale.

    Performance is not a concern: eval() on simple boolean expressions takes
    microseconds, and the RL environment step (physics simulation) dominates
    wall-clock time by orders of magnitude.

    Security is not a concern: the expressions are generated by our own
    extraction pipeline, not from user input. We restrict the eval namespace
    to prevent accidental access to builtins regardless.

Input format
------------
A single string of comma-separated LTL formulas. Each formula must be wrapped
in exactly one of:

    always(...)   — the inner expression must hold at every timestep
    never(...)    — the inner expression must never hold at any timestep

The inner expressions use Python-compatible syntax:
    - Logical:    and, or, not, implies, iff
    - Comparison: >=, <=, >, <, ==, !=
    - Arithmetic: +, -, *, /, abs(), max(), min()
    - Variables:  any valid Python identifier matching a state dict key

Commas inside parentheses (e.g., max(a, b)) are handled correctly by the
top-level splitter.

Output format
-------------
A Python list of strings. Each string is a violation expression that can be
passed to eval() with a state dict as the local namespace. True = violated.

Example:
    >>> ltl_to_violations("always(pump_on implies valve_open), never(temp > 100)")
    ["(pump_on) and not (valve_open)", "temp > 100"]
"""


def ltl_to_violations(ltl_specs: str) -> list[str]:
    """
    Convert comma-separated non-temporal LTL to Python violation expressions.

    Parameters
    ----------
    ltl_specs : str
        Comma-separated LTL formulas, each wrapped in always() or never().

    Returns
    -------
    list[str]
        Violation expressions. eval(expr, namespace) == True means violated.

    Raises
    ------
    ValueError
        If a formula is not wrapped in always() or never().

    Examples
    --------
    >>> ltl_to_violations("always(pump_on implies valve_open)")
    ['(pump_on) and not (valve_open)']

    >>> ltl_to_violations("never(temp > 100)")
    ['temp > 100']

    >>> ltl_to_violations("always(abs(roll) <= 30)")
    ['not (abs(roll) <= 30)']
    """
    violations = []
    for part in _split_top_level(ltl_specs):
        part = part.strip()
        if not part:
            continue
        if part.startswith("always(") and part.endswith(")"):
            inner = part[7:-1].strip()
            violations.append(_negate(inner))
        elif part.startswith("never(") and part.endswith(")"):
            inner = part[6:-1].strip()
            violations.append(inner)
        else:
            raise ValueError(f"Expected always(...) or never(...), got: {part}")
    return violations


def check_violations(obs, violations: list[str], var_map: dict[str, int]) -> float:
    """
    Evaluate violation expressions against an observation array.

    This is the array-indexed variant for use with standard Gym environments
    where observations are numpy arrays. For digital twins that return named
    state dicts, use make_reward_fn() from train.py instead — it skips the
    index lookup entirely since the dict keys already match the LTL variables.

    Parameters
    ----------
    obs : array-like
        Observation vector (numpy array or list of floats).
    violations : list[str]
        Violation expressions from ltl_to_violations().
    var_map : dict[str, int]
        Maps LTL variable names to observation array indices.

    Returns
    -------
    float
        -1.0 if any violation is True, 0.0 otherwise.
    """
    ns = {name: float(obs[idx]) for name, idx in var_map.items()}
    ns["abs"] = abs
    ns["max"] = max
    ns["min"] = min
    for expr in violations:
        if eval(expr, {"__builtins__": {}}, ns):
            return -1.0
    return 0.0


def validate_violations(violations: list[str], var_names: list[str]) -> None:
    """
    Dry-run all violation expressions with zeroed dummy values.

    Call this once before training to catch malformed expressions early —
    a syntax error discovered 10 minutes into a training run wastes GPU time.
    Uses 0.0 for all variables, which exercises the expression parsing
    without making guarantees about logical correctness.

    Parameters
    ----------
    violations : list[str]
        Violation expressions from ltl_to_violations().
    var_names : list[str]
        All variable names that will appear in the state namespace.

    Raises
    ------
    ValueError
        If any expression fails to evaluate, with the expression and error.
    """
    dummy = {name: 0.0 for name in var_names}
    dummy["abs"] = abs
    dummy["max"] = max
    dummy["min"] = min
    for expr in violations:
        try:
            eval(expr, {"__builtins__": {}}, dummy)
        except Exception as e:
            raise ValueError(f"Bad violation expression: {expr!r} -> {e}")


def _negate(expr: str) -> str:
    """
    Negate a propositional formula to produce a violation expression.

    Special-cases the two most common LTL patterns to produce readable output:

        "A implies B"  →  "(A) and not (B)"
            Direct negation of implication. ¬(A → B) ≡ A ∧ ¬B.
            This is the dominant pattern in safety specs (e.g., pump_on → valve_open).

        "A iff B"      →  "bool(A) != bool(B)"
            Biconditional violation. ¬(A ↔ B) ≡ A ⊕ B.
            bool() coercion handles the case where A and B are floats rather
            than strict booleans (e.g., sensor values used as flags).

    All other expressions get a simple "not (...)" wrapper, which Python
    evaluates correctly for any expression returning a truthy/falsy value.
    """
    if " implies " in expr:
        a, b = expr.split(" implies ", 1)
        return f"({a.strip()}) and not ({b.strip()})"
    if " iff " in expr:
        a, b = expr.split(" iff ", 1)
        return f"bool({a.strip()}) != bool({b.strip()})"
    return f"not ({expr})"


def _split_top_level(s: str) -> list[str]:
    """
    Split a string on commas, but only at the top level of parenthesis nesting.

    This allows expressions like always(max(a, b) > 5) to survive splitting.
    The comma inside max(a, b) is at depth 1, so it is not treated as a
    delimiter.

    Parameters
    ----------
    s : str
        Comma-separated LTL formulas.

    Returns
    -------
    list[str]
        Individual formula strings, untrimmed.
    """
    parts, depth, current = [], 0, []
    for ch in s:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(''.join(current))
            current = []
        else:
            current.append(ch)
    if current:
        parts.append(''.join(current))
    return parts
